rss: rss

title: Qarik - go further, faster.
description: >-
  We help companies transform and modernize their IT infrastructure to 
  power growth and drive efficiency. Our business insight and domain 
  knowledge reveal real-world advantage, delivering sustainable change.
twitter_username: qarikgroup
github_username: qarik-group

theme: minima

# plugins from jekyll
plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - shell.nix
  - README.md
  - gemset.nix
