site: Qarik - Go further, faster.
url: #yoururl
title: Qarik - Go futher, faster.
description: >-
  We help companies transform and modernize their IT infrastructure to 
  power growth and drive efficiency. Our business insight and domain 
  knowledge reveal real-world advantage, delivering sustainable change.
permalink: pretty

baseurl: ""

highlighter: rouge

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  authors:
    output: true
    title: Authors
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: authors
    values:
      layout: author
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "assets/imgs"
    values:
      image: true
